#Whether the plugin is enable or not(true/false)
Enabled: true
#Whether the plugin check for update and post the message on console
Update-Check: true
#Whether the chickens will drop the "GoldEgg" (true/false)
ChickenDropGoldEgg: true
#Chance of chicken to drop GoldEgg  
ChickenDropGoldEggChance: 50%
#Captured sound effects, No sound to type (false)
#Sound Support : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
CatchSuccessSound: ENTITY_ARROW_HIT_PLAYER

#The lore of the Catch List GUI
DropSkullLore:
- "&eENTITY TYPE: &a{ENTITY}"
- "&eThe Catcher: &a{PLAYER}"
- "&eCapture Time: &a{TIME}"
- "&eCapture Location: &a{LOCATION}"

#CatchBall on CraftRecipe
Recipe:
    #Whether to turn it on or off
    enabled: true
    #Recipe key
    key:
        #GOLDEGG is the plugin provide custom item
        #Item Support: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/material/package-summary.html
        G: GOLDEGG
    #Recipe
    shape:
    - "GGG"
    - "GGG"
    - "GGG"

#The plugin special item setting
Items:
    CatchBall:
        DisplayName: "&aCat&bch &cball"
        Lore:
        - "&7Used to capture catchable entity"

    GoldEgg:
        DisplayName: "&6GoldEgg"
        Lore:
        - "&7Chickens have a &e{PERCENT}% &7chance of them lay GOLDEGG"
        - "&7Can be used with CraftRecipe to make CatchBall"

#Catcher must have this permission flag to be capture entity. (depend Plugin Residence)
ResidenceFlag:
- animalkilling

#Catcher must have this permission flag to be capture entity. (depend Plugin GriefPrevention)
GriefPreventionFlag:
- Access

Message:
    ConsoleExcuteCommand: "&cThis command can only be executed by player!" 
    NoPermission: "&cYou have no permission!"
    PlayerInventoryFull: "&aYour inventory is full, so item falls at your feet!"
    ArgDoesNotExist: "&aCommands Usage: 
        \n&b/ctb get &7Get special items of plugins.
        \n&b/ctb reload &7Reload plugin.
        \n&b/ctb list &7Lists all catchable entities and states.
        \n&b/ctb add &7Add the entity to the catch list.
        \n&b/ctb remove &7Remove the entity from the catchable list."
    ArgTooMuch: "&cToo many Argument!"
    UnknownCommandArgument: "&cUnknown Argument!"
    SuccessGetBall: "&aSuccessfully get {ITEM}!"
    ReloadSuccess: "&aThe plugin reloaded successfully!"
    CanNotCatchable: "&cThis entity cannot be captured, so &e{BALL} &7fell in &e{LOCATION}."
    BallHitBlock: "&cYou did not hit a entity,So {BALL} fell in {LOCATION}!"
    CatchSuccess: "&aSuccessfully captured {ENTITY} location: {LOCATION}!"
    ItemDoesNotExist: "&cPlease enter the item to be picked up  &7CatchBall | GoldEgg."
    ItemNameError: "&cPlease enter the correct item name  &7CatchBall | GoldEgg!1"
    AddEntityDoesNotExist: "&cPlease enter the name of the entity to be added to the list of captured creatures!"
    UnknownEntityType: "&cUnknown entity type!"
    EntityDoesExists: "&cThe entity already exists in the catchable list!"
    SuccessAddEntity: "&b{ENTITY} &aSuccessfully added to the catchable list!"
    RemoveEntityDoesNotExist: "&cPlease enter the name of the entity to be removed from the catchable list!"
    RemoveEntityNotFound: "&cNo entity found in the catchable list!"
    SuccessRemove: "&aSuccessfully removed from the catchable list &b{ENTITY}!"
    SkullDoesNotFound: "&cThe data stored in the skull is missing!"
    LocationUnsafe: "&cCould not find a safe area to spawn, so this request has been cancelled!"
    NoResidencePermissions: "&cYou can’t spawn entity here because you are lacking {FLAG} permission for this residense!"
    AllowCatchMessage: "&b{ENTITY} &6allow catch: {STATUS} !"