name: CatchBall
main: com.pohuang.CatchBall
author: NUTT1101
description: "§bA plugin that make entity to be catchable.\n§dContect Me: https://discord.gg/sjFufBqguq"  
version: "1.0.0-beta05"
api-version: 1.13
softdepend: [Residence]
permissions:
  catchball.op:
    default: op
commands:
  ctb:
    description: catchball command
    