name: CatchBall
main: com.pohuang.CatchBall
author: NUTT1101
description: "§bA plugin that make entity to be catchable.\n§dContect Me: https://discord.link/nuttPluginClub"  
version: "1.0.3"
api-version: 1.13
softdepend: [Residence, MythicMobs, GriefPrevention]
permissions:
  catchball.op:
    default: op
commands:
  ctb:
    description: "Command Help : /ctb"
    