#Whether the plugin is enabled or not(true/false)
Enabled: true
#Locale, Current support:
#en(English), zh_tw(繁體中文_臺灣)
Locale: en
#Whether the plugin check for update and post the message on console
Update-Check: true
#Whether the chickens will drop the "GoldEgg" (true/false)
ChickenDropGoldEgg: true
#Chance of chicken to drop GoldEgg  
ChickenDropGoldEggChance: 50%
#Captured sound effects, No sound to type (false)
#Sound Support : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
CatchSuccessSound: ENTITY_ARROW_HIT_PLAYER
# "AllowCatchableTamedOwnerIsNull" likely refers to the option of permitting players to capture tamed entities with a null owner, potentially affecting the entity capture mechanics by allowing acquisition of ownerless tamed entities.
AllowCatchableTamedOwnerIsNull: true

#The lore of the Catch List GUI
DropSkullLore:
- "&eENTITY TYPE: &a{ENTITY}"
- "&eThe Catcher: &a{PLAYER}"
- "&eCapture Time: &a{TIME}"
- "&eCapture Location: &a{LOCATION}"

#CatchBall on CraftRecipe
Recipe:
    #Whether to turn it on or off
    enabled: true
    #Recipe key
    key:
        #GOLDEGG is the plugin provide custom item
        #Item Support: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/material/package-summary.html
        G: GOLDEGG
    #Recipe
    shape:
    - "GGG"
    - "GGG"
    - "GGG"

#The plugin special item setting
Items:
    CatchBall:
        DisplayName: "&aCat&bch &cBall"
        Lore:
        - "&7Used to capture catchable entity"

    GoldEgg:
        DisplayName: "&6GoldEgg"
        Lore:
        - "&7Chickens have a &e{PERCENT}% &7chance of them lay GOLDEGG"
        - "&7Can be used with CraftRecipe to make CatchBall"

#Catcher must have this permission flag to be capture entity. (depend on Plugin Residence)
ResidenceFlag:
- animalkilling

#Catcher must have this permission flag to be capture entity. (depend on Plugin GriefPrevention)
GriefPreventionFlag:
- Access

CatchableEntity:
    - SHEEP
