name: CatchBall
main: com.github.nutt1101.CatchBall
author: NUTT1101, MagicTeaMC
description: "§bA plugin that make entity to be catchable.\n§dContact Me: https://discord.gg/zxN2tXb59v"
version: "1.1.10"
api-version: 1.16
softdepend: [Residence, MythicMobs, GriefPrevention]
permissions:
  catchball.op:
    default: op
  catchball.use:
    default: true
commands:
  ctb:
    description: "Command Help : /ctb"
    